# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Asus\Desktop\order_load\searchingForm\_searching_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(302, 365)
        Form.setMinimumSize(QtCore.QSize(302, 365))
        Form.setMaximumSize(QtCore.QSize(302, 365))
        self.searching_list = QtWidgets.QListWidget(Form)
        self.searching_list.setGeometry(QtCore.QRect(15, 60, 271, 291))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.searching_list.setFont(font)
        self.searching_list.setAlternatingRowColors(True)
        self.searching_list.setObjectName("searching_list")
        self.txt_search = QtWidgets.QLineEdit(Form)
        self.txt_search.setGeometry(QtCore.QRect(92, 20, 191, 22))
        self.txt_search.setObjectName("txt_search")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(20, 20, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Arama Yap"))
        self.txt_search.setPlaceholderText(_translate("Form", "Tümü"))
        self.label.setText(_translate("Form", "Anahtar :"))
