# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Asus\Desktop\order_load\Login\_loginForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_form_login(object):
    def setupUi(self, form_login):
        form_login.setObjectName("form_login")
        form_login.resize(396, 592)
        form_login.setStyleSheet("QFrame{\n"
"    \n"
"    background-color: rgb(84, 84, 84);\n"
"    border-radius:15px;\n"
"}\n"
"\n"
"QLineEdit{\n"
"    background:transparent;\n"
"    border:none;\n"
"    color: rgb(141, 141, 141);\n"
"    border-bottom : 1px solid rgb(141, 141, 141);}\n"
"\n"
"QCheckBox::indicator{\n"
"    width: 12px;\n"
"    height: 12px;\n"
"}\n"
"\n"
"QPushButton{\n"
"    border-radius : 10px;\n"
"    background: rgb(141, 141, 141);\n"
"    color : white;\n"
"}\n"
"\n"
"QPushButton::hover{ \n"
"    color:rgb(141, 141, 141) ;\n"
"    background-color: white;\n"
"    border-radius : 10px;\n"
"    border :2px solid  rgb(255, 255, 255);\n"
"\n"
"}")
        self.frame = QtWidgets.QFrame(form_login)
        self.frame.setGeometry(QtCore.QRect(60, 50, 281, 411))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(30, 30, 181, 51))
        font = QtGui.QFont()
        font.setFamily("Ridley Grotesk")
        font.setPointSize(25)
        self.label.setFont(font)
        self.label.setStyleSheet("QLabel[objectName^=\"label\"] {color: white; }")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(70, 70, 181, 51))
        font = QtGui.QFont()
        font.setFamily("Ridley Grotesk")
        font.setPointSize(25)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("QLabel[objectName^=\"label_2\"] {color: white; }")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(180, 120, 51, 21))
        font = QtGui.QFont()
        font.setFamily("Ridley Grotesk")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("QLabel[objectName^=\"label_3\"] {color: orange; }")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(30, 170, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.txt_username = QtWidgets.QLineEdit(self.frame)
        self.txt_username.setGeometry(QtCore.QRect(30, 200, 211, 22))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.txt_username.setFont(font)
        self.txt_username.setText("")
        self.txt_username.setObjectName("txt_username")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(30, 250, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.txt_password = QtWidgets.QLineEdit(self.frame)
        self.txt_password.setGeometry(QtCore.QRect(30, 280, 211, 22))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.txt_password.setFont(font)
        self.txt_password.setText("")
        self.txt_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.txt_password.setObjectName("txt_password")
        self.checkBox = QtWidgets.QCheckBox(self.frame)
        self.checkBox.setGeometry(QtCore.QRect(30, 320, 141, 20))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.checkBox.setFont(font)
        self.checkBox.setChecked(False)
        self.checkBox.setObjectName("checkBox")
        self.btn_logIn = QtWidgets.QPushButton(self.frame)
        self.btn_logIn.setGeometry(QtCore.QRect(20, 360, 241, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_logIn.setFont(font)
        self.btn_logIn.setObjectName("btn_logIn")
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setGeometry(QtCore.QRect(90, 390, 101, 16))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.btn_closeSelf = QtWidgets.QPushButton(self.frame)
        self.btn_closeSelf.setGeometry(QtCore.QRect(250, 10, 21, 20))
        self.btn_closeSelf.setObjectName("btn_closeSelf")

        self.retranslateUi(form_login)
        QtCore.QMetaObject.connectSlotsByName(form_login)

    def retranslateUi(self, form_login):
        _translate = QtCore.QCoreApplication.translate
        form_login.setWindowTitle(_translate("form_login", "Login Form"))
        self.label.setText(_translate("form_login", "ORDER"))
        self.label_2.setText(_translate("form_login", "&LOAD"))
        self.label_3.setText(_translate("form_login", "BETA"))
        self.label_4.setText(_translate("form_login", "Kullanıcı Adı"))
        self.txt_username.setPlaceholderText(_translate("form_login", "Kullanıcı  Adı"))
        self.label_5.setText(_translate("form_login", "Parola"))
        self.txt_password.setPlaceholderText(_translate("form_login", "Parola"))
        self.checkBox.setText(_translate("form_login", "Şifremi Hatırla"))
        self.btn_logIn.setText(_translate("form_login", "Giriş Yap"))
        self.label_6.setText(_translate("form_login", "Copyright © McTOPBAS 2022"))
        self.btn_closeSelf.setText(_translate("form_login", "X"))
