# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Asus\Desktop\order_load_server\server.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1047, 429)
        Form.setMinimumSize(QtCore.QSize(1047, 429))
        Form.setMaximumSize(QtCore.QSize(1047, 429))
        Form.setStyleSheet("QWidget{\n"
"background-color: rgb(0, 0, 0);\n"
"color: rgb(0, 85, 0);}\n"
"\n"
"\n"
"QListWidget{\n"
"background-color: rgb(0, 0, 0);\n"
"color: rgb(0, 85, 0);}")
        self.list_records = QtWidgets.QListWidget(Form)
        self.list_records.setGeometry(QtCore.QRect(20, 70, 1011, 311))
        font = QtGui.QFont()
        font.setFamily("Fixedsys")
        self.list_records.setFont(font)
        self.list_records.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.list_records.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.list_records.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.list_records.setObjectName("list_records")
        self.txt_time = QtWidgets.QLineEdit(Form)
        self.txt_time.setGeometry(QtCore.QRect(20, 20, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Fixedsys")
        font.setPointSize(10)
        self.txt_time.setFont(font)
        self.txt_time.setFrame(False)
        self.txt_time.setAlignment(QtCore.Qt.AlignCenter)
        self.txt_time.setReadOnly(True)
        self.txt_time.setObjectName("txt_time")
        self.txt_console = QtWidgets.QLineEdit(Form)
        self.txt_console.setGeometry(QtCore.QRect(20, 400, 1011, 20))
        font = QtGui.QFont()
        font.setFamily("Fixedsys")
        font.setPointSize(10)
        self.txt_console.setFont(font)
        self.txt_console.setFrame(False)
        self.txt_console.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.txt_console.setReadOnly(False)
        self.txt_console.setObjectName("txt_console")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Order & Load Business Intelligence v1 Server"))
