# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Asus\Desktop\order_load\splash\_splash.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(680, 400)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.dropShadowFrame = QtWidgets.QFrame(self.centralwidget)
        self.dropShadowFrame.setStyleSheet("QFrame {\n"
"    background-color: rgb(84, 84, 84);\n"
"    color    : rgb(220,220,220);\n"
"    border-radius : 10px;\n"
"}")
        self.dropShadowFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.dropShadowFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.dropShadowFrame.setObjectName("dropShadowFrame")
        self.lbl_title = QtWidgets.QLabel(self.dropShadowFrame)
        self.lbl_title.setGeometry(QtCore.QRect(0, 70, 661, 81))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(40)
        font.setBold(False)
        font.setWeight(50)
        self.lbl_title.setFont(font)
        self.lbl_title.setStyleSheet("QLabel{\n"
"\n"
"    color: orange;\n"
"\n"
"}")
        self.lbl_title.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_title.setObjectName("lbl_title")
        self.lbl_title_2 = QtWidgets.QLabel(self.dropShadowFrame)
        self.lbl_title_2.setGeometry(QtCore.QRect(0, 120, 661, 81))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(40)
        font.setBold(False)
        font.setWeight(50)
        self.lbl_title_2.setFont(font)
        self.lbl_title_2.setStyleSheet("QLabel{\n"
"\n"
"color : orange;\n"
"\n"
"}")
        self.lbl_title_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_title_2.setObjectName("lbl_title_2")
        self.label_softwareName = QtWidgets.QLabel(self.dropShadowFrame)
        self.label_softwareName.setGeometry(QtCore.QRect(0, 180, 651, 81))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_softwareName.setFont(font)
        self.label_softwareName.setStyleSheet("color : rgb(152, 152, 152)")
        self.label_softwareName.setAlignment(QtCore.Qt.AlignCenter)
        self.label_softwareName.setObjectName("label_softwareName")
        self.progressBar = QtWidgets.QProgressBar(self.dropShadowFrame)
        self.progressBar.setGeometry(QtCore.QRect(40, 280, 581, 23))
        self.progressBar.setStyleSheet("QProgressBar{\n"
"    \n"
"    background-color: rgb(137, 152, 142);\n"
"    border-style : none;\n"
"    color : rgb(200,200,200);\n"
"    border-radius : 10px;\n"
"    text-align:center;\n"
"}\n"
"\n"
"QProgressBar::chunk{\n"
"    border-radius:10px;\n"
"    \n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.598, x2:0.980296, y2:0.559, stop:0 rgba(255, 170, 0, 255), stop:1 rgba(255, 255, 255, 255));\n"
"    \n"
"}\n"
"")
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.lbl_loading = QtWidgets.QLabel(self.dropShadowFrame)
        self.lbl_loading.setGeometry(QtCore.QRect(0, 280, 661, 81))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lbl_loading.setFont(font)
        self.lbl_loading.setStyleSheet("color : rgb(152, 152, 152)")
        self.lbl_loading.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_loading.setObjectName("lbl_loading")
        self.check_close = QtWidgets.QCheckBox(self.dropShadowFrame)
        self.check_close.setGeometry(QtCore.QRect(40, 330, 81, 20))
        self.check_close.setObjectName("check_close")
        self.check_close.raise_()
        self.lbl_loading.raise_()
        self.label_softwareName.raise_()
        self.lbl_title_2.raise_()
        self.lbl_title.raise_()
        self.progressBar.raise_()
        self.verticalLayout.addWidget(self.dropShadowFrame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lbl_title.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">McTOPBAS</span></p></body></html>"))
        self.lbl_title_2.setText(_translate("MainWindow", "TECHNOLOGY"))
        self.label_softwareName.setText(_translate("MainWindow", "ORDER & LOAD BUSINESS INTELLIGENCE SOFTWARE v1"))
        self.lbl_loading.setText(_translate("MainWindow", "loading..."))
        self.check_close.setText(_translate("MainWindow", "CheckBox"))
